### ISSUE TITLE
Version 3.6.3-0.x86_64.rpm crashes when moving UI windows

### ISSUE THREAD

**Issue by cpiker** [Basile-z/dexed#262] opened 2018-03-02 23:53 UTC
I recently install coedit via the pre-generated RPMs on CentOS Linux 7.4.1708.  Attempting to move the project explorer tab from the left of the editor window to the right produces the following output and the application locks up:

TDockPerformer.DragStop Dropped False False AnchorDockSite20:TAnchorDockHostSite
WARNING: TAnchorDockPageControl.Destroy with LCLRefCount>0. Hint: Maybe the component is processing an event?
TAnchorDockHostSite.SimplifyOneControl Self="DUB project editor" Site="DUB project editor"
TAnchorDockHostSite.Simplify AnchorDockSite11:TAnchorDockHostSite CEDubProjectEditorWidget:TCEDubProjectEditorWidget
TApplication.HandleException Access violation
  Stack trace:
  $0000000000000000
  $000000000050D778
  $000000000042168F
  $000000000050076C
  $00000000006571FC
  $00000000005A6841
  $00000000005B422C
  $00000000005B43DA
  $00007FF99FE8EBDC
TApplication.HandleException Access violation
  Stack trace:
  $00000000005045F1
  $0000000000505D49
  $0000000000505D89
  $0000000000502A79
  $00000000005B4249
  $00000000005B43DA
  $00007FF99FE8EBDC
TApplication.HandleException Access violation
  Stack trace:
  $00007FF99FB18EC8

**Comment by BBasile** [comment] 2018-03-03 04:21
I'm able to see an non fatal AV but not a crash. And this happens when moving it from the right to the left.

More generally docking in Coedit is known for being the number one source of problems. The feature relies on a component i didn't write and it's in beta since forever.

**Comment by BBasile** [comment] 2018-03-04 12:35
According to the stack trace what i've seen is another problem. 
I still cannot reproduce the one you describe.

**Comment by Basile-z** [comment] 2019-02-07 01:38
reminds in #268

**Closed by Basile-z** 2019-02-07 01:38 UTC
Labels: BUG, DOCKING, FCL-LCL, FEEDBACK, HARDTOREPRODUCE
