### ISSUE TITLE
Case where Project search does not work

### ISSUE THREAD

**Issue by vporton** [Basile-z/dexed#447] opened 2019-02-11 00:11 UTC
I opened the https://github.com/dlang/dub project.

I opened the Search & Replace window, choose "Project" for search scope and pressed "Find all".

It gave the message "Unable to open file "/app.d"" and no search results.

**Comment by Basile-z** [comment] 2019-02-11 02:28
I already encountered this one and thought it was fixed...

**Comment by Basile-z** [comment] 2019-02-11 02:32
It works here but i have an idea. In the project inspector, after double click on app.d, look at the filename in the editor status bar and tell me if it's absolute.

**Comment by Basile-z** [comment] 2019-02-11 02:42
The problem is clearly that the  source filename is relative while it should be absolute. Can you describe me exactly who dexed is used ?

- from where is it launched (e.g icons on desktop)
- what is its working directory (e.g that can be a setting in the launcher or that can be the cws if dexed is launched from a console)
- how is the dub project opened (dialog ? drag n drop ? etc)

**Comment by vporton** [comment] 2019-02-11 12:53
It works when launched from Ubuntu Applications, but not when launched from command line in `/home/porton/build/dub` directory.

When launched from this directory, the first file in the project view is `../../../../app.d`.

The DUB project was opened with the dialog.

Dexed 3.7.7.

**Comment by vporton** [comment] 2019-02-11 12:54
The file `../../../../app.d` cannot be opened by double clicking in the project window. There is another file `source/app.d`after it.

**Comment by Basile-z** [comment] 2019-02-13 19:41
I close this one because #448 is the general case. It's likely a DUB bug. The convert command fails depending on the process current dir, or maybe it doesn't use the parameter as expected.

**Comment by Basile-z** [comment] 2019-02-13 19:55
Can you test this patched version https://github.com/Basile-z/dexed/releases/download/v3.7.7/dexed.linux64.fix448.zip and tell me if this fixes the issue please ? Here i verified that #448 is fixed but i'd like to be sure that it was the same problem.

**Comment by Basile-z** [comment] 2019-02-15 08:16
please @vporton can you test the patched version ?

**Closed** 2019-02-18 15:04 UTC
Labels: BUG, FEEDBACK
